app/modules/settings/controllers/DefaultController.php
<?php

/**
 * Settings default controller
 * @author Fred <mconyango@gmail.com>
 */
class DefaultController extends SettingsModuleController
{

    public function init()
    {
        parent::init();
        $this->resourceLabel = Lang::t('Settings');
        $this->resource = SettingsModuleConstants::RES_SETTINGS;
        $this->activeTab = SettingsModuleConstants::TAB_GENERAL;
    }

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',
                'actions' => array('index', 'runtime', 'socialmedia', 'email', 'security', 'payment', 'Payroll', 'map'),
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionIndex()
    {
        $this->hasPrivilege(Acl::ACTION_VIEW);
        $this->pageTitle = Lang::t('General ' . $this->resourceLabel);

        $model = new GeneralSettings();
        $model_class_name = get_class($model);
        if (isset($_POST[$model_class_name])) {
            $this->hasPrivilege(Acl::ACTION_UPDATE);
            $model->attributes = $_POST[$model_class_name];
            if ($model->save()) {
                Yii::app()->user->setFlash('success', Lang::t('SUCCESS_MESSAGE'));
                $this->refresh();
            }
        }

        $this->render('index', array(
            'model' => $model,
        ));
    }

    public function actionRuntime()
    {
        $this->hasPrivilege(Acl::ACTION_VIEW);
        $this->pageTitle = Lang::t('System runtime logs');
        $this->activeTab = SettingsModuleConstants::TAB_RUNTIME;

        $log_file = '';
        if (isset($_POST['log_file'])) {
            $log_file = $_POST['log_file'];
        }

        $base_path = Yii::getPathOfAlias('application.runtime') . DS;
        if (empty($log_file))
            $log_file = $base_path . 'application.log';

        if (isset($_POST['clear'])) {
            $this->hasPrivilege(Acl::ACTION_DELETE);
            if (file_exists($log_file)) {
                @unlink($log_file);
            }
        }

        $log_files = Common::getDirectoryFiles($base_path . 'application.log*');

        $this->render('runtime', array(
            'log_files' => $log_files,
            'log_file' => $log_file,
        ));
    }

    public function actionMap()
    {
        $this->hasPrivilege(Acl::ACTION_VIEW);
        $this->activeTab = SettingsModuleConstants::TAB_MAP;
        $this->pageTitle = Lang::t('Google map settings');

        if (isset($_POST['settings'])) {
            $this->hasPrivilege(Acl::ACTION_UPDATE);
            foreach ($_POST['settings'] as $key => $value) {
                Yii::app()->settings->set(SettingsModuleConstants::SETTINGS_GOOGLE_MAP, $key, $value);
            }

            Yii::app()->user->setFlash('success', Lang::t('SUCCESS_MESSAGE'));
            $this->refresh();
        }
        $settings = Yii::app()->settings->get(SettingsModuleConstants::SETTINGS_GOOGLE_MAP, array(
            SettingsModuleConstants::SETTINGS_GOOGLE_MAP_API_KEY,
            SettingsModuleConstants::SETTINGS_GOOGLE_MAP_DEFAULT_CENTER,
            SettingsModuleConstants::SETTINGS_GOOGLE_MAP_DEFAULT_MAP_TYPE,
            SettingsModuleConstants::SETTINGS_GOOGLE_MAP_CROWD_MAP_ZOOM,
            SettingsModuleConstants::SETTINGS_GOOGLE_MAP_SINGLE_VIEW_ZOOM,
            SettingsModuleConstants::SETTINGS_GOOGLE_MAP_DIRECTION_MAP_ZOOM,
        ));

        $this->render('map', array(
            'settings' => $settings,
        ));
    }

}

app/modules/settings/views/default/_generalSettingsForm.php
<?php
$form = $this->beginWidget('CActiveForm', array(
    'id' => 'general-settings-form',
    'enableAjaxValidation' => false,
    'htmlOptions' => array(
        'class' => 'form-horizontal',
    )
        ));
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->pageTitle; ?></h3>
    </div>
    <div class="panel-body">
        <?php echo CHtml::errorSummary($model, ''); ?>
        <fieldset>
            <legend><?php echo Lang::t('Company details') ?></legend>
            <div class="form-group">
                <?php echo CHtml::activeLabelEx($model, 'company_name', array('class' => 'col-md-2 control-label')); ?>
                <div class="col-md-4">
                    <?php echo CHtml::activeTextField($model, 'company_name', array('class' => 'form-control', 'maxlength' => 60)); ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo CHtml::activeLabelEx($model, 'app_name', array('class' => 'col-md-2 control-label')); ?>
                <div class="col-md-4">
                    <?php echo CHtml::activeTextField($model, 'app_name', array('class' => 'form-control', 'maxlength' => 30)); ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo CHtml::activeLabelEx($model, 'company_email', array('class' => 'col-md-2 control-label')); ?>
                <div class="col-md-4">
                    <?php echo CHtml::activeTextField($model, 'company_email', array('class' => 'form-control', 'maxlength' => 128)); ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo CHtml::activeLabelEx($model, 'default_timezone', array('class' => 'col-md-2 control-label')); ?>
                <div class="col-md-4">
                    <?php echo CHtml::activeDropDownList($model, 'default_timezone', SettingsTimezone::model()->getListData('name', 'name', false), array('class' => 'form-control')); ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo CHtml::activeLabelEx($model, 'country_id', array('class' => 'col-md-2 control-label')); ?>
                <div class="col-md-4">
                    <?php echo CHtml::activeDropDownList($model, 'country_id', SettingsCountry::model()->getListData('id', 'name', false), array('class' => 'form-control')); ?>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend><?php echo Lang::t('Display options') ?></legend>
            <div class="form-group">
                <?php echo CHtml::activeLabelEx($model, 'items_per_page', array('class' => 'col-md-2 control-label')); ?>
                <div class="col-md-4">
                    <?php echo CHtml::activeDropDownList($model, 'items_per_page', Common::generateIntergersList(5, 100, 5), array('class' => 'form-control')); ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo CHtml::activeLabelEx($model, 'theme', array('class' => 'col-md-2 control-label')); ?>
                <div class="col-md-4">
                    <?php echo CHtml::activeDropDownList($model, 'theme', GeneralSettings::themeOptions(), array('class' => 'form-control')); ?>
                </div>
            </div>
        </fieldset>
    </div>
    <div class="panel-footer clearfix">
        <div class="pull-right">
            <a class="btn btn-default btn-sm" href="<?php echo UrlManager::getReturnUrl(Yii::app()->createUrl('default/index')) ?>"><i class="fa fa-times"></i> <?php echo Lang::t('Cancel') ?></a>
            <button class="btn btn-sm btn-primary" <?php echo!$this->showLink($this->resource, Acl::ACTION_UPDATE) ? 'disabled="disabled"' : null ?> type="submit"><i class="fa fa-check"></i> <?php echo Lang::t('Save Changes') ?></button>
        </div>
    </div>
</div>
<?php $this->endWidget(); ?>

app/modules/settings/views/default/index.php
<?php
$this->breadcrumbs = array(
    $this->pageTitle,
);
?>
<div class="row">
    <div class="col-md-2">
        <?php $this->renderPartial('settings.views.layouts._menu') ?>
    </div>
    <div class="col-md-10">
        <?php $this->renderPartial('_generalSettingsForm', array('model' => $model)) ?>
    </div>
</div>

app/modules/settings/views/default/map.php
<?php
$this->breadcrumbs = array(
    $this->pageTitle,
);
?>
<div class="row">
    <div class="col-md-2">
        <?php $this->renderPartial('settings.views.layouts._menu') ?>
    </div>
    <div class="col-md-10">
        <?php echo CHtml::beginForm(Yii::app()->createUrl($this->route), 'POST', array('class' => 'form-horizontal')) ?>
        <div class="panel panel-default">
            <div class="panel-heading"><h4 class="panel-title"><?php echo CHtml::encode($this->pageTitle) ?></h4></div>
            <div class="panel-body">
                <div class="form-group">
                    <label class="control-label col-md-3"><?php echo Lang::t('API Key') ?> : </label>
                    <div class="col-md-4">
                        <?php echo CHtml::textField('settings[' . SettingsModuleConstants::SETTINGS_GOOGLE_MAP_API_KEY . ']', $settings[SettingsModuleConstants::SETTINGS_GOOGLE_MAP_API_KEY], array('class' => 'form-control', 'required' => true,)) ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3"><?php echo Lang::t('Default Map Center') ?> : </label>
                    <div class="col-md-4">
                        <?php echo CHtml::textField('settings[' . SettingsModuleConstants::SETTINGS_GOOGLE_MAP_DEFAULT_CENTER . ']', $settings[SettingsModuleConstants::SETTINGS_GOOGLE_MAP_DEFAULT_CENTER], array('class' => 'form-control', 'required' => true,)) ?>
                        <p class="help-block text-muted">Latitude,Longitude</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3"><?php echo Lang::t('Default map type') ?> : </label>
                    <div class="col-md-4">
                        <?php echo CHtml::dropDownList('settings[' . SettingsModuleConstants::SETTINGS_GOOGLE_MAP_DEFAULT_MAP_TYPE . ']', $settings[SettingsModuleConstants::SETTINGS_GOOGLE_MAP_DEFAULT_MAP_TYPE], GmapUtils::mapTypeOptions(), array('class' => 'form-control')) ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3"><?php echo Lang::t('Default crowd map zoom') ?> : </label>
                    <div class="col-md-4">
                        <?php echo CHtml::dropDownList('settings[' . SettingsModuleConstants::SETTINGS_GOOGLE_MAP_CROWD_MAP_ZOOM . ']', $settings[SettingsModuleConstants::SETTINGS_GOOGLE_MAP_CROWD_MAP_ZOOM], GmapUtils::zoomOptions(), array('class' => 'form-control')) ?>
                        <p class="help-block text-muted"><?php echo Lang::t('Default zoom for a map showing many locations') ?></p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3"><?php echo Lang::t('Default single view zoom') ?> : </label>
                    <div class="col-md-4">
                        <?php echo CHtml::dropDownList('settings[' . SettingsModuleConstants::SETTINGS_GOOGLE_MAP_SINGLE_VIEW_ZOOM . ']', $settings[SettingsModuleConstants::SETTINGS_GOOGLE_MAP_SINGLE_VIEW_ZOOM], GmapUtils::zoomOptions(), array('class' => 'form-control')) ?>
                        <p class="help-block text-muted"><?php echo Lang::t('Default zoom for a map showing one location') ?></p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3"><?php echo Lang::t('Default direction map zoom') ?> : </label>
                    <div class="col-md-4">
                        <?php echo CHtml::dropDownList('settings[' . SettingsModuleConstants::SETTINGS_GOOGLE_MAP_DIRECTION_MAP_ZOOM . ']', $settings[SettingsModuleConstants::SETTINGS_GOOGLE_MAP_DIRECTION_MAP_ZOOM], GmapUtils::zoomOptions(), array('class' => 'form-control')) ?>
                        <p class="help-block text-muted"><?php echo Lang::t('Default zoom for get direction map') ?></p>
                    </div>
                </div>
            </div>
            <div class="panel-footer clearfix">
                <div class="pull-right">
                    <a class="btn btn-default btn-sm" href="<?php echo Yii::app()->createUrl('default/index') ?>"><i class="fa fa-times"></i> <?php echo Lang::t('Cancel') ?></a>
                    <button class="btn btn-sm btn-primary" type="submit"><?php echo Lang::t('Save Changes') ?></button>
                </div>
            </div>
        </div>
        <?php echo CHtml::endForm() ?>
    </div>
</div>

app/modules/settings/views/default/runtime.php
<?php
$this->breadcrumbs = array(
    $this->pageTitle,
);
?>
<div class="row">
    <div class="col-md-2">
        <?php $this->renderPartial('settings.views.layouts._menu') ?>
    </div>
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-body">
                <?php echo CHtml::beginForm(Yii::app()->createUrl($this->route), 'post', array('id' => 'log_file_form', 'class' => 'form-inline', 'onchange' => 'MyUtils.triggerSubmit("#log_file_form")')) ?>
                <?php echo CHtml::dropDownList('log_file', $log_file, $log_files, array('class' => 'form-control')) ?>
                <button class="btn btn-danger btn-sm" name="clear">Clear this log</button>
                <?php echo CHtml::endForm() ?>
                <hr/>
                <pre style="max-height: 500px;overflow-y: auto">
                                <code><?php echo file_exists($log_file) ? CHtml::encode(trim(file_get_contents($log_file))) : '' ?></code>
                </pre>
            </div>
        </div>
    </div>
</div>