app/controllers/ReportsController.php
<?php

class ReportsController extends FleetModuleController {

    public function init() {
        $this->resource = FleetModuleConstants::RES_FLEET;
        $this->resourceLabel = 'Fleet Valuation Reports';
        $this->activeMenu = FleetModuleConstants::MENU_FLEET;
        $this->activeTab = FleetModuleConstants::TAB_FLEET_REPORTS;
        parent::init();
    }

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('partner', 'index', 'vehicles', 'report', 'print', 'invoices', 'insuranceRenewed', 'withoutCover', 'insurance', 'valuationPartner', 'valuationClient', 'test', 'genReportClient'),
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        // $this->hasPrivilege();
        $this->pageTitle = Lang::t($this->resourceLabel);

        $this->render('index', array(
        ));
    }

    public function actionPrint($id) {
        $this->pageTitle = 'Valuation Report';
        $model = FleetValuations::model()->findByPk($id);
        $dat = FleetBookings::model()->findByPk($model->booking_id);
        $vehicle = FleetVehicles::model()->findByPk($dat->vehicle_id);
        $photos = FleetValuationPhotos::model()->findAll('valuation_id=:t1', array(':t1' => $id));
        $this->render('_valuation_html', array('model' => $model, 'vehicle' => $vehicle, 'photos' => $photos), False, true);
    }

    public function actionReport($id) {
        $model = FleetValuations::model()->findByPk($id);
        $dat = FleetBookings::model()->findByPk($model->booking_id);
        $vehicle = FleetVehicles::model()->findByPk($dat->vehicle_id);
        $photos = FleetValuationPhotos::model()->findAll('valuation_id=:t1', array(':t1' => $id));

        // $mPDF1 = Yii::app()->epdf->mpdf();
        $mPDF1 = Yii::app()->ePdf->mpdf('', 'A5');
        $stylesheet = file_get_contents(Yii::getPathOfAlias('webroot') . '/themes/smartadmin/css/mpdfstyleA4.css');
        $mPDF1->WriteHTML($stylesheet, 1);
        $mPDF1->WriteHTML($this->renderPartial('_valuation_report', array('model' => $model, 'vehicle' => $vehicle, 'photos' => $photos), true), 2);
        $mPDF1->Output();
    }

    public function actionPartner() {
        $this->pageTitle = Lang::t('Valuation Report');
        //$user = Users::model()->findByPk(Yii::app()->user->id);
        // $partner = $user->partner_id;
        $this->activeTab = FleetModuleConstants::TAB_FLEET_REPORTS;
        $partner = Yii::app()->user->partner_id;
        $partner = Yii::app()->user->partner_id;
         $condition = 'approved=1 and partner_id='.$partner;
        $model = FleetBookingsView::model()->searchModel(array('partner_id' => $partner), 100000000, '',$condition);
        $this->render('partner', array(
            'model' => $model,
        ));
    }

    public function actionInvoices($date_from = null, $date_to = null) {
        $this->pageTitle = Lang::t('Valuation Invoices');
        //$user = Users::model()->findByPk(Yii::app()->user->id);
        // $partner = $user->partner_id;
        $this->activeTab = FleetModuleConstants::TAB_FLEET_VEHICLE_ASSIGNMENTS;
        $partner = Yii::app()->user->partner_id;
         $condition = 'approved=1 and partner_id='.$partner;
        if ($date_from != null || $date_to != null) {
           

            if ($date_from != null) {
                $condition.=" AND `valuation_date`>'" . $date_from . "'";
            }if ($date_to != null) {
                $condition.=" AND `valuation_date`<'" . $date_to . "'";
            }if ($date_from != null&&$date_to !=null) {
                $condition.=" AND `valuation_date`' between '" . $date_from . "' and '" . $date_to . "'";
            }

            $model = FleetBookingsView::model()->searchModel(array('partner_id' => $partner), 100000000, '',$condition);
            $posted = 1;
        } else {
            $model = FleetBookingsView::model()->searchModel(array('partner_id' => $partner), 100000000, '',$condition);
        }
        $this->render('invoice', array(
            'model' => $model,
            'date_from'=>$date_from,'date_to'=>$date_to
        ));
    }

    public function actionValuationPartner($from = NULL, $to = NULL) {
        $this->activeTab = FleetModuleConstants::TAB_PARTNER;
        $this->pageTitle = Lang::t('Valuation Report by Par+.tner');
        $partners = SettingsPartners::model()->findAll();
        if (!$this->checkDate($from) && !$this->checkDate($to)) {
            $from = $to = null;
        }
        if (!empty($from) && !empty($to)) {
            $model = array();
            foreach ($partners as $row) {

                $criteria = new CDbCriteria();
                $criteria->condition = 'client_type=:t1 AND partner_id=:t2';
                $criteria->params = array(':t1' => 2, ':t2' => $row->id);
                $criteria->addBetweenCondition('date_booked', $from, $to);
                $result = FleetValManager::model()->findAll($criteria);
                $no = count($result);
                $cost = $this->computeCost($result);
                array_push($model, array('id' => $row->id, 'no' => $no, 'cost' => $cost));
            }
        }
        if (isset($_GET['gen']) && !empty($model)) {
            $this->actionGenReportPartner($model, $from, $to);
        }
        if (!empty($from) && !empty($to)) {

            $this->render('valuation_partner', array(
                'partners' => $partners,
                'model' => $model,
                'from' => $from,
                'to' => $to,
            ));
        } else {
            $this->render('valuation_partner', array('model' => array(), 'from' => $from, 'to' => $to,
            ));
        }
    }

    public function actionValuationClient($from = NULL, $to = NULL) {

        $this->activeTab = FleetModuleConstants::TAB_CLIENT;
        $this->pageTitle = Lang::t('Valuation Report by Client');
        $clients = SettingsClients::model()->findAll();
        if (!$this->checkDate($from) && !$this->checkDate($to)) {
            $from = $to = null;
        }
        if (!empty($from) && !empty($to)) {
            $model = array();
            foreach ($clients as $row) {

                $criteria = new CDbCriteria();
                $criteria->condition = 'client_id=:t2';
                $criteria->params = array(':t2' => $row->id);
                $criteria->addBetweenCondition('date_booked', $from, $to);
                $result = FleetValManager::model()->findAll($criteria);
                $no = count($result);
                $cost = $this->computeCost($result);
                array_push($model, array('id' => $row->id, 'no' => $no, 'cost' => $cost));
            }
        }
        if (isset($_GET['gen']) && !empty($model)) {
            $this->actionGenReportClient($model, $from, $to);
        }
        if (!empty($from) && !empty($to)) {

            $this->render('valuation_client', array(
                'clients' => $clients,
                'model' => $model,
                'from' => $from,
                'to' => $to,
            ));
        } else {
            $this->render('valuation_client', array('model' => array(), 'from' => $from, 'to' => $to,
            ));
        }
    }

    public function actionGenReportPartner($model, $from, $to) {
        // $mPDF1 = Yii::app()->epdf->mpdf();
        $mPDF1 = Yii::app()->ePdf->mpdf('', 'A5');
        $stylesheet = file_get_contents(Yii::getPathOfAlias('webroot') . '/themes/smartadmin/css/mpdfstyleA4.css');
        $mPDF1->WriteHTML($stylesheet, 1);
        $mPDF1->WriteHTML($this->renderPartial('pdf/valuation_partner', array('model' => $model, 'from' => $from, 'to' => $to), true), 2);
        $mPDF1->Output();
    }

    public function actionGenReportClient($model, $from, $to) {
        // $mPDF1 = Yii::app()->epdf->mpdf();
        $mPDF1 = Yii::app()->ePdf->mpdf('', 'A5');
        $stylesheet = file_get_contents(Yii::getPathOfAlias('webroot') . '/themes/smartadmin/css/mpdfstyleA4.css');
        $mPDF1->WriteHTML($stylesheet, 1);
        $mPDF1->WriteHTML($this->renderPartial('pdf/valuation_client', array('model' => $model, 'from' => $from, 'to' => $to), true), 2);
        $mPDF1->Output();
    }

    public function actionTest($model, $from, $to) {

        $this->renderPartial('pdf/valuation_partner', array('model' => $model, 'from' => $from, 'to' => $to), true);
    }

    public function actionVehicles($t) {
        $this->hasPrivilege();
        $valid_t = array(
            FleetModuleConstants::PARAM_VEHICLE_IN_USE,
            FleetModuleConstants::PARAM_VEHICLE_NOT_IN_USE,
        );
        if (!in_array($t, $valid_t))
            $t = FleetModuleConstants::PARAM_VEHICLE_IN_USE;

        $this->pageTitle = Lang::t($t === FleetModuleConstants::PARAM_VEHICLE_IN_USE ? 'Vehicles in use' : 'Vehicles not in use');

        $this->render('vehicles', array(
            'model' => FleetVehicles::model()->searchModel(array('inuse' => $t === FleetModuleConstants::PARAM_VEHICLE_IN_USE ? 1 : 0), $this->settings[SettingsModuleConstants::SETTINGS_ITEMS_PER_PAGE]),
        ));
    }

    public function actionVehiclesInService() {
        $this->pageTitle = Lang::t('Vehicles currently taken for servicing');

        $this->render('vehiclesInService', array(
            'model' => FleetVehicleServicing::model()->searchModel(array('status' => FleetVehicleServicing::STATUS_IN_SERVICE), $this->settings[SettingsModuleConstants::SETTINGS_ITEMS_PER_PAGE]),
        ));

app/views/reports/_filter.php
<?= CHtml::form(Yii::app()->createUrl($this->route, $this->actionParams), 'get', ['class' => '']) ?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?= Lang::t('Filter By:') ?></h3>
    </div>
    <div class="panel-body">
        <div class="row">
		<input type="hidden" name="posted" value="1">
            <div class="col-md-3">
                <?= CHtml::label('Date From', "", ['class' => 'control-label']) ?>
                <br/>
				 <?= CHtml::activeTextField('date_from', $date_from, ['class' => 'form-control show-datepicker']); ?>
				<?php //echo CHtml::activeDropDownList($model, 'corporation_id', HrOrganizations::model()->getListData('id', 'name'), array('class' => 'select2')); ?>&nbsp;&nbsp;
            </div>
         
			<div class="col-md-3">
			 <?= CHtml::label('Date To', "", ['class' => 'control-label']) ?>
                <br/>
				<?= CHtml::activeTextField('date_to', $date_to,   ['class' => 'form-control show-datepicker']); ?>
			</div>
			<div class="col-md-1">
                <br/>
                <button class="btn btn-primary" type="submit"><?= Lang::t('Go') ?></button>
            </div>
            <div class="col-md-1">
                <br/>
                <a class="btn btn-default"
                   href="<?= Yii::app()->createUrl($this->route) ?>"><?= Lang::t('Clear') ?></a>
            </div>
        </div>
    </div>
</div>
<?= CHtml::endForm() ?>

app/views/reports/_valuation_report.php
<?php
$baseUrl = Yii::app()->theme->baseUrl;
$cs = Yii::app()->getClientScript();
?>

<div class="container-fluid ">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-no-border">
                <tr><td><img src="<?php echo Yii::app()->theme->baseUrl . '/images/logo.jpg' ?>" class="pull-left padding-10 " alt="" style="max-width: 150px;">
                    </td><td style="color:#900;">VALUATION REPORT</td><td class="pull-right padding-10" style="text-align: right; font-size: 9px; color: #006dcc;"><u>Head Office:</u><br>Vic Preston Opp. Nairobi University<br>Next to Anniversary Towers<br>P.O. Box 4640-00200<br>Nairobi, Kenya<br>Phone:+254 020 263 77 22<br>Email:info@geo-sat.net<br>:www.geo-sat.net</td></tr>
            </table>
            <table class="table table-no-border">

                <tbody>
                    <tr>
                        <td class="dat-label"><strong>INSURER:</strong></td>
                        <td class="dat"><?php echo FleetInsuranceProviders::model()->get($model->insurer, "name"); ?></td>
                        <td class="dat-label"><strong>POLICY NO:</strong></td>
                        <td class="dat"><?php echo $model->booking->policy_no; ?></td>
                        <td class="dat-label"><strong>CERTIFICATE NO:</strong></td>
                        <td class="dat"><?php echo $model->certificate_no; ?></td>


                    </tr>
                    <tr>
                        <td class="dat-label"><strong>EXPIRE DATE:</strong></td>
                        <td class="dat"><?php echo $model->expiry_date; ?></td>
                        <td class="dat-label"><strong>PURPOSE:</strong></td>
                        <td class="dat"><?php echo $model->booking->purpose; ?></td>                      
                        <td class="dat-label"><strong>SERIAL NO:</strong></td>
                        <td class="dat"><?php echo $model->booking->serial_no; ?></td>

                    </tr>
                    <tr>
                        <td class="dat-label"><strong>ISSUED BY:</strong></td>
                        <td class="dat"><?php echo $model->booking->branch->name; ?></td>
                        <td class="dat-label"><strong>CLIENT:</strong></td>
                        <td class="dat"><?php echo SettingsClients::model()->get($vehicle->client_id, "name"); ?></td>
                        <td class="dat-label"><strong>TEL :</strong> </td>
                        <td class="dat"><?php echo SettingsClients::model()->get($vehicle->client_id, "phone_no"); ?></td>
                    </tr>
                </tbody>

            </table>
        </div>
    </div>
    <br>

    <div class="col-md-12"><p class="top-info">A brief examination and road test has been carried out on the vehicle described below, the findings are as follows;</p></div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-no-border">
                <thead>
                </thead>
                <tbody >

                    <tr>
                        <td class="dat-label"><strong>REG NO:</strong></td>
                        <td class="dat"><?php echo $vehicle->vehicle_reg; ?></td>
                        <td class="dat-label"><strong>MAKE:</strong> </td>
                        <td class="dat"><?php echo FleetMake::model()->get($vehicle->make_id, "name"); ?></td>

                        <td class="dat-label"><strong>COLOUR:</strong></td>
                        <td class="dat"><?php echo $vehicle->color; ?></td>
                    </tr>
                    <tr>
                        <td class="dat-label"><strong>ENGINE NO: </strong> </td>
                        <td class="dat"><?php echo $vehicle->engine_number; ?></td>

                        <td class="dat-label"><strong>TYPE:</strong> </td>
                        <td class="dat"><?php echo FleetVehicleTypes::model()->get($vehicle->vehicle_type_id, "name"); ?></td>
                        <td class="dat-label"><strong>ODOMETER (KM): </strong></td>
                        <td class="dat"><?php echo number_format($vehicle->odometer_reading, 0); ?></td>
                    </tr>
                    <tr>
                        <td class="dat-label"><strong>MODEL:</strong></td>
                        <td class="dat"><?php echo FleetModel::model()->get($vehicle->model_id, "name"); ?></td>
                        <td class="dat-label"><strong>REG DATE:</strong> </td>
                        <td class="dat"><?php echo $vehicle->reg_date; ?></td>

                        <td class="dat-label"><strong>CHASIS NO:</strong></td>
                        <td class="dat"><?php echo $vehicle->chasis_number; ?></td>
                    </tr>
                    <tr><td class="dat-label"><strong>MAN YEAR:</strong></td>
                        <td class="dat"><?php echo $vehicle->man_year; ?></td>

                        <td class="dat-label"><strong>RATING (CC):</strong></td>
                        <td class="dat"><?php echo $vehicle->capacity; ?></td>
                        <td class="dat-label"><strong>ORIGIN:</strong></td>
                        <td class="dat"><?php echo $vehicle->origin; ?></td>
                    </tr>
                    <tr>
                        <td class="dat-label"><strong>GEAR BOX:</strong></td>
                        <td class="dat"><?php echo $model->gearbox; ?></td>
                        <td class="dat-label"><strong>FUEL:</strong></td>
                        <td class="dat"><?php echo $model->fuel; ?></td>

                        <td class="dat-label"><strong>TYPE OF LIGHTS:</strong></td>
                        <td class="dat"><?php echo $model->lighting_type; ?></td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="dat-label"><strong>EXTRAS:</strong></td>
                        <td class="dat"><?php echo $vehicle->extras; ?></td>
                        <td>&nbsp;</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <hr>

    <div class="row">
        <div class="col-md-12">
            <table class="table table-no-border">
                <thead>
                </thead>
                <tbody>

                    <tr>
                        <td class="dat-label"><strong>ANTI THEFT:</strong></td>
                        <td class="dat"><?php echo $model->anti_theft; ?></td>
                        <td class="dat-label"><strong>COACH WORK:</strong>  </td>
                        <td class="dat"><?php echo $model->coachwork; ?></td>

                        <td class="dat-label"><strong>TYRES:</strong> </td>
                        <td class="dat"><?php echo $model->tyres_make; ?></td>
                    </tr>
                    <tr> <td class="dat-label"><strong>MECHANICAL:</strong> </td>
                        <td class="dat"><?php echo $model->mechanial; ?></td>

                        <td class="dat-label"><strong>EXAMINER: </strong></td>
                        <td class="dat"><?php echo $model->examiner; ?></td>
                        <td class="dat-label"><strong>PLACE OF INSP: </strong></td>
                        <td class="dat"><?php echo $model->place_of_inspection; ?></td>

                    </tr>
                    <tr>
                        <td class="dat-label"><strong>ELECTRICAL:</strong></td>
                        <td class="dat"><?php echo $model->electrical; ?></td>
                        <td class="dat-label"><strong>INSP DATE:</strong></td>
                        <td class="dat"><?php echo $model->val_date; ?></td>

                        <td class="dat-label"><strong>GENERAL CONDITION:</strong></td>
                        <td class="dat"><?php echo $model->gen_condition; ?></td>
                    </tr>
                    <tr> <td class="dat-label"><strong>RADIO:</strong></td>
                        <td class="dat"><?php echo $model->radio; ?></td>

                        <td class="dat-label"><strong>WINDSCREEN</strong></td>
                        <td class="dat"><?php echo $model->note_vale; ?></td>
                        <td class="dat-label"><strong>DESTINATION:</strong></td>
                        <td class="dat"><?php echo $model->booking->destination->name; ?></td>
                    </tr>
                    <tr>
                        <?php if ($model->booking->purpose == 'FINANCE') { ?>
                            <td class="dat-label"><strong>MARKET VALUE:</strong></td>
                        <?php } else {
                            ?>
                            <td class="dat-label"><strong>ASSESSED VALUE:</strong></td><?php }
                        ?>
                        <td class="dat"><?php echo $model->market_value; ?></td>
                        <td class="dat-label"><strong>AMOUNT IN WORDS:</strong></td>
                        <td class="dat"><?php
                            $amount = (int) $model->market_value;

                            $data = $this->widget('ext.NumtoWord.NumtoWord', array('num' => $amount));
                            print $data->result;
                            ?></td>
                    </tr>
                    <?php if ($model->booking->purpose == 'FINANCE') { ?><tr>
                            <td class="dat-label"><strong>FORCED VALUE:</strong></td>
                            <td class="dat"><?php echo $model->forced_value; ?></td>
                            <td class="dat-label"><strong>AMOUNT IN WORDS:</strong></td>
                            <td class="dat"><?php
                                $amount = (int) $model->forced_value;

                                $data = $this->widget('ext.NumtoWord.NumtoWord', array('num' => $amount));
                                print $data->result;
                                ?></td>
                        </tr><?php } ?>
                </tbody>
            </table>

            <table class="table table-no-border">
                <tbody>
                    <tr>
                        <td class="dat-label"><strong>SIGNATURE:</strong></td>
                        <td class="dat"><img src="<?php echo Yii::app()->theme->baseUrl . '/images/signature.jpg' ?>" class="pull-left padding-10 " alt="" style="max-width: 150px;"></td>
                        <td ><strong>FOR AND ON BEHALF OF GEO-SAT SOLUTIONS LTD</strong></td>

                    </tr>
                    <tr>
                        <td class="dat-label"><strong>DATE:</strong></td>
                        <td class="dat"><?php echo date('Y-m-d'); ?></td>
                        <td class="dat-label"><strong>REMARKS:</strong></td>
                        <td class="dat bottom-info " style="color:#ED1C24;"><b><?php echo $model->remarks; ?></b></td>
                    </tr>

                </tbody>
            </table>


        </div>
    </div>
    <div class="col-md-12" class="bottom-info">    <p>
            N.B.This report reflects the estimated Market Value of the subject value in its present condition at the time of valuation. Any future changes will take into account any changes,due to usage e.t.c
        </p></div>
    <h2 class="page-title txt-color-blueDark">
        <?php echo Lang::t('Images') ?>
    </h2>


    <?php $this->renderPartial('_pic_grid_reports', array('model' => $model, 'photos' => $photos)); ?>




</div>




</div>

app/views/reports/dueServicing.php
<?php
$this->breadcrumbs = array(
    $this->pageTitle,
);
?>
<div class="row">
    <div class="col-md-2">
        <?php $this->renderPartial('fleet.views.layouts._tab') ?>
    </div>
    <div class="col-md-10">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title txt-color-blueDark">
                    <i class="fa fa-fw fa-truck"></i> <?php echo CHtml::encode($this->pageTitle) ?>
                    <small> <?php echo Common::formatDate($from, 'M j, Y') ?> - <?php echo Common::formatDate($to, 'M j, Y') ?> </small>
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="well well-sm">
                    <?php echo CHtml::beginForm(Yii::app()->createUrl($this->route), 'GET', array('class' => 'form-inline')) ?>
                    <?php echo Lang::t('From') ?>: <?php echo CHtml::textField('from', $from, array('class' => 'form-control show-datepicker')) ?>&nbsp;&nbsp;
                    <?php echo Lang::t('To') ?>: <?php echo CHtml::textField('to', $to, array('class' => 'form-control show-datepicker')) ?>
                    <button class="btn btn-smx btn-default" type="submit"><?php echo Lang::t('GO') ?></button>
                    <?php echo CHtml::endForm() ?>
                </div>
            </div>
        </div>
        <?php $this->renderPartial('fleet.views.reports.grids._dueServicing', array('model' => $model, 'from' => $from, 'to' => $to)); ?>
    </div>
</div>

app/views/reports/index.php
<?php
$this->breadcrumbs = array(
    $this->pageTitle,
);
?>
<div class="row">
    <div class="col-sm-12 col-md-2">
        <?php $this->renderPartial('fleet.views.layouts._tab') ?>
    </div>
    <div class="col-sm-12 col-md-10">
        <div class="well">
            <div class="row">
                <div class="col-sm-12">
                    <h1 class="page-title txt-color-blueDark">
                        <?php echo CHtml::encode($this->pageTitle) ?>
                    </h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="list-group">

                        <?php if (Yii::app()->user->user_level == 'PARTNER') { ?>
                            <a href="<?php echo $this->createUrl('reports/valuationPartner') ?>" class="list-group-item"><?php echo Lang::t('Vehicle Valuation report') ?> <span class="pull-right"><i class="fa fa-chevron-right"></i></span></a>
                        <?php } else { ?>
                            <a href="<?php echo $this->createUrl('reports/vehicles', array('t' => FleetModuleConstants::PARAM_VEHICLE_IN_USE)) ?>" class="list-group-item"><?php echo Lang::t('Vehicles in use') ?> <span class="pull-right"><i class="fa fa-chevron-right"></i></span></a>
                            <a href="<?php echo $this->createUrl('reports/vehicles', array('t' => FleetModuleConstants::PARAM_VEHICLE_NOT_IN_USE)) ?>" class="list-group-item"><?php echo Lang::t('Vehicles not in use') ?> <span class="pull-right"><i class="fa fa-chevron-right"></i></span></a>
                            <a href="<?php echo $this->createUrl('reports/valuationPartner') ?>" class="list-group-item"><?php echo Lang::t('Valuation report') ?> <span class="pull-right"><i class="fa fa-chevron-right"></i></span></a>
                                <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/reports/insuranceRenewal.php
<?php
$this->breadcrumbs = array(
    $this->pageTitle,
);
?>
<div class="row">
    <div class="col-md-2">
        <?php $this->renderPartial('fleet.views.layouts._tab') ?>
    </div>
    <div class="col-md-10">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title txt-color-blueDark">
                    <i class="fa fa-fw fa-truck"></i> <?php echo CHtml::encode($this->pageTitle) ?>
                    <small> <?php echo Common::formatDate($from, 'M j, Y') ?> - <?php echo Common::formatDate($to, 'M j, Y') ?> </small>
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="well well-sm">
                    <?php echo CHtml::beginForm(Yii::app()->createUrl($this->route), 'GET', array('class' => 'form-inline')) ?>
                    <?php echo Lang::t('From') ?>: <?php echo CHtml::textField('from', $from, array('class' => 'form-control show-datepicker')) ?>&nbsp;&nbsp;
                    <?php echo Lang::t('To') ?>: <?php echo CHtml::textField('to', $to, array('class' => 'form-control show-datepicker')) ?>
                    <button class="btn btn-smx btn-default" type="submit"><?php echo Lang::t('GO') ?></button>
                    <?php echo CHtml::endForm() ?>
                </div>
            </div>
        </div>
        <?php $this->renderPartial('fleet.views.reports.grids._insuranceRenewal', array('model' => $model, 'from' => $from, 'to' => $to)); ?>
    </div>
</div>

app/views/reports/valuation_client.php
<?php
$this->breadcrumbs = array(
    $this->pageTitle,
);
?>
<div class="row">
    <div class="col-md-2">
        <?php $this->renderPartial('fleet.views.layouts._tab') ?>
    </div>
    <div class="col-md-10">
        <div class="row">
            <?php $this->renderPartial('fleet.views.reports._tab') ?>
            <br>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="well well-sm">
                    <?php echo CHtml::beginForm(Yii::app()->createUrl($this->route), 'GET', array('class' => 'form-inline')) ?>
                    <?php echo Lang::t('From') ?>: <?php echo CHtml::textField('from', $from, array('class' => 'form-control show-datepicker')) ?>&nbsp;&nbsp;
                    <?php echo Lang::t('To') ?>: <?php echo CHtml::textField('to', $to, array('class' => 'form-control show-datepicker')) ?>
                    <button class="btn btn-smx btn-default" type="submit"><?php echo Lang::t('GO') ?></button>
                    <?php echo CHtml::endForm() ?>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-info"></i><?php echo Lang::t('   Valuation Information') ?></h3>
            </div>
            <?php $this->renderPartial('fleet.views.reports.grids._valuation_client', array('model' => $model, 'from' => $from, 'to' => $to)); ?>
        </div>
    </div>
</div>

app/views/reports/vehicles.php
<?php
$this->breadcrumbs = array(
    $this->pageTitle,
);
?>
<div class="row">
    <div class="col-md-2">
        <?php $this->renderPartial('fleet.views.layouts._tab') ?>
    </div>
    <div class="col-md-10">
        <?php $this->renderPartial('fleet.views.reports.grids._vehicles', array('model' => $model)); ?>
    </div>
</div>